version: '3.4'

services:
  coinbazaar.transfer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5001:80"
      - "5002:443"
    volumes:
      - ~/ASP.NET/Https:/root/.aspnet/https:ro
  coinbazaar.wallet.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5003:80"
      - "5004:443"
    volumes:
      - ~/ASP.NET/Https:/root/.aspnet/https:ro

  coinbazaar.transfer.esconsumer.grpc:
    volumes:
      - ~/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
