version: '3.4'

services:
  coinbazaar.transfer.api:
    image: ${DOCKER_REGISTRY-}coinbazaartransferapi
    build:
      context: .
      dockerfile: CoinBazaar.Transfer.API/Dockerfile

  coinbazaar.wallet.api:
    image: ${DOCKER_REGISTRY-}coinbazaarwalletapi
    build:
      context: .
      dockerfile: CoinBazaar.Wallet.API/Dockerfile

